name: utsfurs-site

services:
    server:
        image: hugomods/hugo:exts-non-root-0.145.0
        command: server -D
        volumes:
            - ./:/src
            - ~/hugo_cache:/tmp/hugo_cache
        ports:
            - 9595:1313
